#! /bin/sh

workspaces() {
    name=1
    for monitor in `bspc query -M`; do
        bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6'
        let name++
    done
}
workspaces

bspc config border_width         2
bspc config window_gap           8
bspc config split_ratio          0.50
bspc config bottom_padding       0
bspc config top_padding          24

bspc config focused_border_color "#737373"
bspc config normal_border_color  "#525252"
bspc config active_border_color  "#474747"

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config single_monocle        false
bspc config focus_follows_pointer false

# fix pointer
xsetroot -cursor_name left_ptr

## Workspace 1 (Classes)
bspc rule -a zoom desktop='^1' follow=on focus=on
bspc rule -a Chat desktop='^1' state=floating
bspc rule -a FreeTube desktop='^1' follow=on focus=on

## Workspace 2 (Web Browser)
bspc rule -a LibreWolf desktop='^2' follow=on focus=on
bspc rule -a Chromium desktop='^2' follow=on focus=on
bspc rule -a Brave-browser desktop='^2' follow=on focus=on
bspc rule -a qutebrowser desktop='^2' follow=on focus=on
bspc rule -a Firefox desktop='^2' follow=on focus=on

## Workspace 3 (Terminal) (Launch alacritty at startup)
bspc rule -a Alacritty -o desktop='^3' follow=on focus=on

## Workspace 4 (Social)
bspc rule -a discord desktop='^4' follow=on focus=on
bspc rule -a Zathura desktop='^4' follow=on focus=on state=tiling

## Workspace 5 (Files)
bspc rule -a Thunar desktop='^5' follow=on focus=on
bspc rule -a Transmission-gtk desktop='^5' follow=on focus=on state=floating

## Workspace 6 (Media)
# Email
bspc rule -a Geary desktop='^6' follow=on focus=on
bspc rule -a vlc desktop='^6' follow=on focus=on
bspc rule -a obs desktop='^6' follow=on focus=on
bspc rule -a mpv desktop='^6' follow=on focus=on
bspc rule -a Gimp desktop='^4' follow=on focus=on
bspc rule -a Gimp-2.10 desktop='^4' follow=on focus=on

bspc rule -a dmenu state=floating

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad Gpick)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst polybar

poly_cfg="$HOME/.config/polybar/config.ini"

polybar -r --config=$poly_cfg left &
polybar -r --config=$poly_cfg center-left &
polybar -r --config=$poly_cfg center &
polybar -r --config=$poly_cfg center-tray &
polybar -r --config=$poly_cfg center-right &
polybar -r --config=$poly_cfg right &

# Launch notification daemon
dunst \
-geom "280x50-10+38" -frame_width "1" -font "Roboto Medium 10" \
-lb "#282828FF" -lf "#dfbf8eFF" -lfr "#a9b665FF" \
-nb "#282828FF" -nf "#dfbf8eFF" -nfr "#a9b665FF" \
-cb "#282828FF" -cf "#ea6962FF" -cfr "#ea6962FF" &

# Launch keybindings daemon
sxhkd &

# start compositor
picom &

# Feh
feh --bg-fill ~/.config/bspwm/wallpapers/sugigata.png &

# Remap control key and caps lock
xmodmap ~/.config/bspwm/swapkeys -display :0 &

# Redshift night time
pgrep -x redshift > /dev/null || redshift -l 14.599512:120.984222 &

~/mpd-notify-song-change.py

# If third workspace empty, open a terminal there
if [ -z $(bspc query -N -d 3) ]
then
    alacritty -e "$HOME/.config/sxhkd/new_tmux_terminal.sh" &
fi
