#! /bin/sh

# Set cursor theme
xsetroot -cursor_name left_ptr

# sxhkd - keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

# Redshift - Night light
pgrep -x redshift > /dev/null || redshift -l 14.599512:120.984222 &

# Picom compositor
pgrep -x picom > /dev/null || picom &

# Polybar
pkill polybar ; polybar mybar &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         2
bspc config window_gap           10
bspc config left_padding         8
bspc config right_padding        8
bspc config top_padding          23
bspc config bottom_padding       0

# Colors
bspc config focused_border_color "#646D82"
bspc config normal_border_color "#434957"
bspc config presel_feedback_color "#98c379"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

##################
## Window rules ##
##################

### App-specific stats
bspc rule -a Gpick state=floating
bspc rule -a File-roller state=floating
bspc rule -a Lxappearance state=floating

### Launch apps on specific workspaces

## Workspace 1 (Classes)
bspc rule -a zoom desktop='^1' follow=on focus=on
bspc rule -a Chat desktop='^1' state=floating

## Workspace 2 (Web Browser)
bspc rule -a Brave-browser desktop='^2' follow=on focus=on
bspc rule -a qutebrowser desktop='^2' follow=on focus=on
bspc rule -a LibreWolf desktop='^2' follow=on focus=on
bspc rule -a Firefox desktop='^2' follow=on focus=on

bspc rule -a FreeTube desktop='^2' follow=on focus=on

## Workspace 3 (Terminal)
bspc rule -a Alacritty desktop='^3' follow=on focus=on

## Workspace 4 (Social)
bspc rule -a discord desktop='^4' follow=on focus=on

## Workspace 5 (Files)
bspc rule -a Thunar desktop='^5' follow=on focus=on
bspc rule -a Transmission-gtk desktop='^5' follow=on focus=on

## Workspace 6 (Work/Study)
# Email
bspc rule -a Geary desktop='^6' follow=on focus=on

# FreeOffice suite
bspc rule -a tm desktop='^6' follow=on focus=on
bspc rule -a pm desktop='^6' follow=on focus=on
bspc rule -a pr desktop='^6' follow=on focus=on

# LibreOffice
bspc rule -a libreoffice-startcenter desktop='^6' follow=on focus=on

# Anki
bspc rule -a Anki desktop='^6' follow=on focus=on state=floating

## Workspace 7 (Multimedia)
#bspc rule -a vlc desktop='^7' follow=on focus=on state=fullscreen
#bspc rule -a Gimp-2.10 desktop='^7' follow=on focus=on
#bspc rule -a Audacity desktop='^7' follow=on focus=on

## Workspace 8 (Settings)
bspc rule -a Xfce4-settings-editor desktop='^8' follow=on focus=on state=floating
bspc rule -a Xfce4-settings-manager desktop='^8' follow=on focus=on state=floating

#feh --bg-fill ~/.config/bspwm/wallpaper/voidlogo.png &
feh --bg-fill ~/Downloads/smogforest.jpeg &

# Remap control key and caps lock
xmodmap ~/.config/bspwm/swapkeys -display :0 &

