#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         3
bspc config window_gap           9
bspc config left_padding         2
bspc config right_padding        2

# Colors
bspc config focused_border_color "#5599D1"
bspc config normal_border_color  "#2D2D2D"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Polybar
polybar mybar &
# Picom
picom  --vsync --backend glx -cb -o 0.50 -i 1 --unredir-if-possible --glx-no-stencil -D 8 --glx-no-rebind-pixmap -m 100 &
# Background
feh --bg-fill ~/Pictures/gnomewall2.png &
# Night light
killall redshift && redshift -l 14.599512:120.984222 &
# Remap control key and caps lock
xmodmap ~/.config/i3/swapkeys -display :0 &
