#!/bin/sh

display_workspace_name() {
    workspace=$(bspc query -D -d focused --names)

    echo $workspace
}

display_workspace_name
bspc subscribe desktop node_transfer | while read -r _ ; do
    display_workspace_name
done
