#!/bin/sh

# wlsunset -l 14.6 -L 121 &
swaybg -m fill -i ~/Pictures/skytain-gruv.png & 
XDG_CURRENT_DESKTOP=Unity waybar &

start_audio () {
    /usr/bin/pipewire &
    /usr/bin/pipewire-pulse &
    /usr/bin/wireplumber &
    mpd & 

    # Start NoiseTorch input and set the default microphone to NoiseTorch
    sleep 1 &
    noisetorch -i &
    sleep 1
    pactl set-default-source "NoiseTorch Microphone" &
}

start_audio &

foot --server &

riverctl map normal Super Return spawn 'footclient $HOME/.config/scripts/new_tmux_terminal.sh' &
riverctl map normal Super+Shift Return spawn 'footclient' &

riverctl map normal Super apostrophe spawn "wayout --toggle HDMI-A-1" &

riverctl map normal Super y spawn "$HOME/.config/scripts/toggle-night-mode" &

# dmenu replacement with the gruvbox material color, of course
riverctl map normal Super D spawn "$HOME/.config/scripts/fuzzel-themed" &

riverctl map normal Super E spawn "emote" &

# Audio/backlight controls
riverctl map normal Super U spawn "$HOME/.config/scripts/change_audio --dec" &
riverctl map normal Super I spawn "$HOME/.config/scripts/change_audio --inc" &
# riverctl map normal Super O spawn "$HOME/.config/scripts/change_brightness --dec" &
# riverctl map normal Super P spawn "$HOME/.config/scripts/change_brightness --inc" &
riverctl map normal Super O spawn "$HOME/.config/scripts/change_audio --mute" &

# MPD controls
riverctl map normal Super+Shift U spawn "mpc prev" &
riverctl map normal Super+Shift I spawn "mpc next" &
riverctl map normal Super+Shift O spawn "mpc seekthrough -3" &
riverctl map normal Super+Shift P spawn "mpc seekthrough +3" &
riverctl map normal Super+Shift bracketleft spawn "mpc toggle" &
riverctl map normal Super+Shift bracketright spawn "mpc seek 0 && mpc play" &

# Take screenshot with grim + slurp + swappy
riverctl map normal Super N spawn "~/.config/scripts/takeshot-fast" &
riverctl map normal Super m spawn "~/.config/scripts/takeshot-fast --full" &

riverctl map normal Super 8 spawn "~/.config/scripts/open_book" &

# Super+Q to close the focused view
riverctl map normal Super Q close &

# Super+Shift+E to exit river
riverctl map normal Super+Shift E exit &

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next &
riverctl map normal Super K focus-view previous &

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next &
riverctl map normal Super+Shift K swap previous &

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next &
riverctl map normal Super Comma focus-output previous &

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next &
riverctl map normal Super+Shift Comma send-to-output previous &

# Super+H and Super+L to decrease/increase the main ratio of rivercarro(1)
riverctl map normal Super H send-layout-cmd rivercarro "main-ratio -0.05" &
riverctl map normal Super L send-layout-cmd rivercarro "main-ratio +0.05" &

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivercarro(1)
riverctl map normal Super+Shift H send-layout-cmd rivercarro "main-count +1" &
riverctl map normal Super+Shift L send-layout-cmd rivercarro "main-count -1" &

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100 &
riverctl map normal Super+Alt J move down 100 &
riverctl map normal Super+Alt K move up 100 &
riverctl map normal Super+Alt L move right 100 &

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left &
riverctl map normal Super+Alt+Control J snap down &
riverctl map normal Super+Alt+Control K snap up &
riverctl map normal Super+Alt+Control L snap right &

# Super+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100 &
riverctl map normal Super+Alt+Shift J resize vertical 100 &
riverctl map normal Super+Alt+Shift K resize vertical -100 &
riverctl map normal Super+Alt+Shift L resize horizontal 100 &

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view &

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view &

for i in $(seq 1 8)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags &

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags &

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags &

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags &
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags &
riverctl map normal Super+Shift 0 set-view-tags $all_tags &

riverctl map normal Super S focus-previous-tags &

# Super+Space to toggle float
riverctl map normal Super R toggle-float &

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen &

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivercarro "main-location top" &
riverctl map normal Super Right send-layout-cmd rivercarro "main-location right" &
riverctl map normal Super Down  send-layout-cmd rivercarro "main-location bottom" &
riverctl map normal Super Left  send-layout-cmd rivercarro "main-location left" &

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough &

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough &

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal &

# Set background and border color
riverctl border-color-focused 0x494949 &
riverctl border-color-unfocused 0x656565 &
riverctl border-width 3 &

riverctl focus-follows-cursor normal &

# Set keyboard repeat rate
riverctl set-repeat 50 300 &

# Make certain views start floating
riverctl float-filter-add app-id float &
riverctl float-filter-add title "popup title with spaces" &
riverctl float-filter-add app-id "Gpick" &

riverctl xcursor-theme "phinger-cursors" 32 &

gnome_schema="org.gnome.desktop.interface"
gsettings set "$gnome_schema" gtk-theme "Gruvbox-Material-Dark" &
gsettings set "$gnome_schema" icon-theme "Gruvbox-Material-Dark" &
gsettings set "$gnome_schema" font-name "Roboto 11" &
gsettings set "$gnome_schema" cursor-theme "phinger-cursors" &
gsettings set "$gnome_schema" cursor-size "32" &

VARIABLES="DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE"
riverctl spawn "dbus-update-activation-environment ${VARIABLES:- --all}"

# swayidle timeout 1200 "sudo zzz" &

# RGB controls
openrgb --server &
openrgb --startminimized &
openrgb --profile gruvbox-green &

# Set and exec into the default layout generator, rivercarro.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivercarro
exec rivercarro -no-smart-gaps -inner-gaps 6 -outer-gaps 6 -main-ratio 0.55
