#!/bin/sh

step="10"

notify () {
    brightness="$2"

    if [[ "$brightness" -gt "80" ]]; then
        icon="🌕"
    elif [[ "$brightness" -gt "60" ]]; then
        icon="🌖"
    elif [[ "$brightness" -gt "40" ]]; then
        icon="🌗"
    elif [[ "$brightness" -gt "20" ]]; then
        icon="🌘"
    else
        icon="🌑"
    fi

    dunstify -h string:x-dunst-stack-tag:brightness -h int:value:"$brightness" \
             -t 2500 "$icon $brightness%"
}

if [[ "$1" = "--inc" ]]; then
    xbacklight -inc "$step" -time 0
    notify -inc "$(xbacklight -get)"

elif [[ "$1" == "--dec" ]]; then
    xbacklight -dec "$step" -time 0
    notify -dec "$(xbacklight -get)"

else
    echo "usage: change_brightness [--inc]/[--dec]"
    exit 1
fi
