#!/bin/sh
project="$1"

print_repo_data() {
    projectname=$(basename "$project")
    commitcount=$(git --git-dir=$gitdir \
                  rev-list --all --count)

    printf "\e[0;93m\e[1;34m $projectname \e[0m\n"

    printf "\e[0;93m\e[0;34m branch\e[0m   "

    git --git-dir=$gitdir \
    rev-parse --abbrev-ref HEAD

    printf "\e[0;93m\e[0;34m commits\e[0m  "
    echo $commitcount
}

list_files() {
    export EXA_COLORS="di=33"
    ~/.local/bin/exa -1 --icons -T -L 3 --git-ignore \
    --group-directories-first -l --no-permissions \
    --no-user --no-filesize --changed --no-time $HOME/"$project"
}

display_output() {
    clear
    echo "$repo_data"
    printf "\e[0;93m\e[0;34m language \e[0m"
    echo -e "$language_emojis\n"

    echo "$1"

    sleep "$sleep_interval"
}

main () {
    sleep_interval="5"

    repo_data=$(print_repo_data)
    echo "$repo_data"

    file_tree=$(list_files)
    onefetch_output=$(onefetch --output json ~/"$project" |
                      ~/.local/bin/onefetch-wrapper)

    language_emojis=$(echo "$onefetch_output" | sed 1q)
    onefetch_output=$(echo "$onefetch_output" | sed 1d | sed 1d)

    display_output "$file_tree"

    while true; do
        display_output "$onefetch_output"
        display_output "$file_tree"
    done
}

gitdir="$(echo "$HOME/")$(echo "$project")$(echo "/.git")"

if [ -e $gitdir ]; then
    main
else
    list_files
fi
