#!/usr/bin/env bash

projects=$(\
           find \
               ~/projects \
               ~/projects/axyl \
               ~/forks \
               ~/study \
               -mindepth 1 -maxdepth 1 -type d |

           sed --regexp-extended "s/^\/home\/[^\/]+\///g")

selected=$(echo "$projects" |

           fzf --border=none --reverse --prompt="  ➡️  " --ansi --cycle \
               --header="🚀 tmux-sessionizer" --header-first \
               --pointer="🔥" \
               --no-mouse \
               --no-info \
               --padding 0,1 --margin 0 \
               --color="prompt:blue,prompt:bold,border:green,border:dim" \
               --color="fg+:yellow" \
               --color="hl:underline,hl+:underline,hl:magenta,hl+:magenta" \
               --color="info:green" \
               --color="spinner:green,spinner:dim" \
               --preview="$HOME/.config/scripts/mts-show-project '{}'" \
               --preview-window=border-left,58%)

if [ $? != 0 ]; then exit; fi

selected="$HOME/${selected}"
selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t $selected_name 2> /dev/null; then

    tmux new-session -ds $selected_name -c $selected \
        -x 300 -y 300 -n "nvim" "sleep 0.05 ; nvim $selected ; zsh"

    tmux new-window -t $selected_name:2 -d -c $selected zsh
fi

tmux switch-client -t $selected_name
