#!/bin/python3
# fzf does not display the colors of onefetch correctly so I have to do this
import fileinput
import json

RESET = "\033[0m"
RED = "\033[0;31m"
GREEN = "\033[0;32m"
ORANGE = "\033[0;33m"
BLUE = "\033[0;34m"
MAGENTA = "\033[0;35m"
CYAN = "\033[0;36m"
YELLOW = "\033[0;93m"
BOLD = "\033[1m"

language_emojis = {
        "C": f"{BLUE}{RESET}",
        "C++": f"{BLUE}{RESET}",
        "C#": f"{MAGENTA}{RESET}",
        "Rust": f"{RED}{RESET}",
        "Go": f"{CYAN}{RESET}",
        "Swift": f"{ORANGE}ﯣ{RESET}",
        "Java": f"{ORANGE}{RESET}",
        "Python": f"{YELLOW}{RESET}",
        "Lua": f"{BLUE}{RESET}",
        "Ruby": f"{RED}{RESET}",
        "Julia": "",
        "PHP": f"{MAGENTA}{RESET}",
        "Dart": f"{CYAN}{RESET}",
        "Shell": "",
        "HTML": f"{ORANGE}{RESET}",
        "CSS": f"{BLUE}{RESET}",
        "Sass": f"{MAGENTA}ﳪ{RESET}",
        "JavaScript": f"{YELLOW}{RESET}",
        "TypeScript": f"{BLUE}ﯤ{RESET}",
        }

language_colors = {
        "C": f"{BLUE}",
        "C++": f"{BLUE}",
        "C#": f"{MAGENTA}",
        "Rust": f"{RED}",
        "Go": f"{CYAN}",
        "Swift": f"{ORANGE}",
        "Java": f"{ORANGE}",
        "Python": f"{YELLOW}",
        "Lua": f"{BLUE}",
        "Ruby": f"{RED}",
        "PHP": f"{MAGENTA}",
        "Dart": f"{CYAN}",
        "HTML": f"{ORANGE}",
        "CSS": f"{BLUE}",
        "Sass": f"{MAGENTA}",
        "JavaScript": f"{YELLOW}",
        "TypeScript": f"{BLUE}",
        }

output = ""
for line in fileinput.input():
    output += str(line)
repo_json = json.loads(output)

languages: list[str] = repo_json['languages']
language_format = ""
for language in languages:
    language_format += f"{language}, "
language_format = language_format[:-2]

# Determine the color of the field names
if len(languages) > 1 and languages[0] in language_colors:
    output_color = language_colors[languages[0]]
else:
    output_color = YELLOW

# Format the onefetch output
format = ""
format += f"{output_color}{BOLD}Project:{RESET} {repo_json['repoName']}"
if repo_json['numberOfBranches'] > 0:
    format += f" ({repo_json['numberOfBranches']} \
{'branches' if repo_json['numberOfBranches'] > 1 else 'branch'})"
format += f"\n{output_color}{BOLD}Created:{RESET} {repo_json['creationDate']}\n"
format += f"{output_color}{BOLD}Language:{RESET} {language_format}\n"
format += f"{output_color}{BOLD}Last change:{RESET} {repo_json['lastChange']}\n"
format += f"{output_color}{BOLD}Lines of code:{RESET} {repo_json['linesOfCode']}\n"
format += f"{output_color}{BOLD}Size:{RESET} {repo_json['repoSize']}\n"
if repo_json['license']:
    format += f"{output_color}{BOLD}License:{RESET} {repo_json['license']}\n"

# Print emojis
for language in languages:
    if language in language_emojis:
        print(language_emojis[language], end=" ")
print()
print()

print(format)
