#!/bin/python3

from os import path
from subprocess import call


def main() -> int:
    file_name = "/tmp/arch_updates"

    if not path.exists(file_name):
        return 1

    file = open(file_name, "r")
    lines = file.read().split("\n")

    pkg_list = [line.split(" ")[0] for line in lines]
    pkg_list = [pkg_name for pkg_name in pkg_list if pkg_name != ""]

    pkg_count = len(pkg_list)

    if pkg_count != 0:
        pkg_str = f"📦 packages ({pkg_count})\n" + "\n".join(pkg_list)
    else:
        pkg_str = "Everything up to date.\nEnjoy your day! 😊"

    call("dunstify --hints string:x-dunst-stack-tag:arch_updates "
         f'"{pkg_str}"', shell=True)

    return 0


if __name__ == "__main__":
    exit(main())
