#!/bin/python3
"""arch_updates: print the number of updates in Arch-based systems

   Requirements: `pacman-contrib` package
   > sudo pacman -Syu pacman-contrib
"""

import subprocess


def format_output(pkg_count: int) -> str:
    if pkg_count > 1:
        word = "updates"
    elif pkg_count == 1:
        word = "update"
    else:
        return "😋 up-to-date"

    return f"🧀 {pkg_count} {word}"


def main() -> int:
    proc = subprocess.run("checkupdates", capture_output=True)

    # 2 is the return code for `checkupdates` if everything is up-to-date
    if proc.returncode not in [0, 2]:
        return 1

    output = proc.stdout

    # Write output to tmp file
    with open("/tmp/arch_updates", "w") as file:
        file.write(output.decode("utf-8"))

    # Packages to update are separated by newlines
    update_count = output.count(b'\n')

    print(format_output(update_count), flush=True)

    return 0


if __name__ == "__main__":
    exit(main())
