#!/bin/python3
"""notify_arch_updates: display a notification about packages
   to update in Arch Linux

   Requirements: `pacman-contrib` package
   > sudo pacman -Syu pacman-contrib

   You also need `arch_update` script running in your bar
   or in other programs periodically.
"""

from os import path
from subprocess import call


def main() -> int:
    file_name = "/tmp/arch_updates"

    if not path.exists(file_name):
        return 1

    file = open(file_name, "r")
    lines = file.read().split("\n")

    pkgs = [line for line in lines if line != ""]
    pkg_count = len(pkgs)

    pkg_format: list[dict] = [
                     {
                      "name": pkg.split(" ")[0],
                      "old_version": pkg.split(" ")[1],
                      "new_version": pkg.split(" ")[3],
                     }
                     for pkg in pkgs]

    formatted_str = ""
    for pkg in pkg_format:
        formatted_str += f"{pkg['name']}\n"
        formatted_str += f"  {pkg['old_version']} -> {pkg['new_version']}\n"

    if pkg_count != 0:
        pkg_str = f"{formatted_str}\n"
    else:
        pkg_str = "Everything up to date.\nEnjoy your day! 😊"

    call("dunstify --hints string:x-dunst-stack-tag:arch_updates "
         f'"packages 📦 ({pkg_count})" '
         f'"{pkg_str}"', shell=True)

    return 0


if __name__ == "__main__":
    exit(main())
